# Generated by Django 3.2.4 on 2024-01-21 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='notelike',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notelikes', to='notes.notes'),
        ),
    ]
