# Generated by Django 3.2.4 on 2024-01-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
