# Generated by Django 3.2.4 on 2024-01-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
