# Generated by Django 3.2.4 on 2024-01-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
